### PR TITLE
Feature/242 combine name and id

### PR DESCRIPTION
**Pull request by maxdiebold-erg**
## Related Issues:
* [EQ-242](https://jira.epa.gov/browse/EQ-242)

## Main Changes:
* Combined "name" and "id" columns throughout the user interface. This was accomplished by creating calculated columns in the database, where necessary.
* Moved column output sorting entirely to the `config/profiles.ts` file.
* Moved filter dependency config to the `config/fields.ts` file. In the current case, this works well as a simplification because columns have similar dependency behavior across profiles.
* Fixed a bug/typo that was causing 'year' values to be dropped when initially passed into the URL.

## Steps To Test:
1. Run the ETL locally.
2. Go to http://localhost:3000/attains/assessmentUnits.
3. Open the _Assessment Unit ID_ field and confirm that the values are displayed in the format _id - name_.
4. Select an ID.
5. Copy the URL, open a new tab, and confirm that the field is populated with the previously selected value.
6. Verify that the _Organization ID_ "source select" drop-down still properly filters the ID values.
7. Execute a query with a newly added ID field, and verify the columns returned include the corresponding "id" and "name" fields but not the "displayName" field.

### N.B.
I didn't remove any indexes from the "id" or "name" fields, but I did remove them from the materialized views. This is because they won't be used (in **v1**) to query column values or to execute queries from the UI, but they'll still benefit queries that are made directly to the server.

### CODE REVIEW

**Review by cschwinderg — CHANGES_REQUESTED** [review]
This works great locally, but this won't work when we go to dev/stage. Dev/stage use an s3 extension to move data from the ords extracts to the postgres tables. This means the table structures need to match the structure of the extracts exactly.

I put down a couple of ideas below on how to get this to work once it gets to dev/stage. 

Option 2 will probably be easier to implement in the short term. 

Option 1 will be a little more difficult to implement, but it is probably a better long term solution. It will reduce the amount of data that we send to our endpoints. This is because we will only be passing the id instead of `<id> - <name>`, which will make it less likely that users will hit character limitations for get requests. It will reduce the size of data and indexes, because the display name columns will only be in the materialized views where we have already filtered down to unique values.


### Option 1: Only have displayName columns in the materialized views
Update the code for creating materialized views to have a display name column that combines the id and name columns. 

Here is an example of what the query might look like:
```
CREATE MATERIALIZED VIEW IF NOT EXISTS schema_1682530672722.assessments_assessments
AS
 SELECT DISTINCT 
 	assessments.assessmentunitid,
	concat_ws(' - ', assessments.assessmentunitid, assessments.assessmentunitname) as assessmentunitdisplayname,
        assessments.organizationid,
	concat_ws(' - ', assessments.organizationid, assessments.organizationname) as organizationdisplayname,
        assessments.organizationtype,
        assessments.region,
        assessments.state
   FROM schema_1682530672722.assessments
   
   WITH DATA;
```
I left the `assessmentunitid` column in so the UI can use that in the `data` endpoints.


The `tableConfig.js` may need to look something like this:
```
materializedViews: [
      {
        name: 'actions_assessments',
        columns: [
          { name: 'assessmentunitid' },
          { 
            name: 'assessmentunitdisplayname',
            columns: [
              'assessmentunitid',
              'assessmentunitname',
            ]
          },
          { name: 'organizationid' },
          { 
            name: 'organizationdisplayname',
            columns: [
              'organizationid',
              'organizationname',
            ]
          },
          { name: 'organizationtype' },
          { name: 'region' },
          { name: 'state' },
        ],
      }
  ],
```

The drop downs will need to be updated so searching works against the display name field, but the underlying value is just the id. The ui will need to be updated to pass the id, instead of the display name value, to the `data` endpoints. 

### Option 2: Add an extra step to the ETL to add the display name columns after data is loaded, but before materialized views are created
To get this to work you would need to remove the display name fields from the `createQuery`s, `insertColumn`s and `transform`s. Then you would need to add a new step, in between loading data and creating materialized views, that adds a generated column to the tables that concatenate the desired columns. Here is what those queries would look like:
```
ALTER TABLE schema_1682530672722.assessments
ADD COLUMN "assessmentunitdisplaynametest" varchar(308)
GENERATED ALWAYS AS (assessmentunitid || ' - ' || assessmentunitname) STORED;
```
You would need to update the `tableConfig.js` file so that it has `generatedColumns` values which will allow us to configure these generated columns. 

Everything else would essentially work the same.

**Comment by cschwinderg** [comment]
> It shouldn't hurt to leave the ID fields in the MVs, but I don't think we're hitting the MVs in any of the `data` endpoints.
> 
> I had thought about just passing the ID as the value, which is why initially I was going to just grab both component columns. Without knowing the component values, we'll need to rely on splitting the string. That's easy enough when using the same separator, but if it varies down the road we can always add the separator to the config.

I don't think we should rely on splitting the string. It is possible for states to include ` - ` in their assessment unit names and probably even in their assessment unit ids. I think we will need to have the dropdowns store label = `<id> - <name>` and value = `<id>`. Then when we call the `data` endpoints we just pass the ids.

**Comment by maxdiebold-erg** [comment]
Okay, I do agree the string splitting would be problematic. So to have just the `<id>` then we'll need to get a label and a value field back. That's similar to the initial approach of retrieving both the`<id>` and `<name>` fields and concatenating them on the client, but I suppose it might cut back on database computing a bit.

**Comment by cschwinderg** [comment]
Couldn't we update the `/:profile/values/:column` endpoint to return back both the value (`<id>`) and the label (`<id> - <name>`)? 

We would update our `tableConfig.js` file to have a config for the id column. If the `idColumn` isn't provided then we just assume the value and label are the same column.

```
materializedViews: [
      {
        name: 'actions_assessments',
        columns: [
          { name: 'assessmentunitid' },
          { 
            name: 'assessmentunitdisplayname',
            idColumn: 'assessmentunitid',
            columns: [
              'assessmentunitid',
              'assessmentunitname',
            ]
          },
          { name: 'organizationid' },
          { 
            name: 'organizationdisplayname',
            idColumn: 'organizationid',
            columns: [
              'organizationid',
              'organizationname',
            ]
          },
          { name: 'organizationtype' },
          { name: 'region' },
          { name: 'state' },
        ],
      }
  ],
```

Then the query in `queryColumnValues` would be updated to return something like this for queries against assessmentunitdisplayname:

```
[
  { value: 'AS-27O', label: 'AS-27O - Nuuuli Pala-Ocean' },
  { value: 'TN06010102237_1000', label: 'TN06010102237_1000 - Muddy Creek' },
  ...
]
```

And something like this for region:
```
[
  { value: '02', label: '02' },
  { value: '03', label: '03' },
  ...
]
```

**Comment by maxdiebold-erg** [comment]
Yep I follow you, I'm just not sure it will perform better than requesting paired column values and joining them in the client, and it comes with a pretty heavy maintenance/configuration cost.

**Comment by cschwinderg** [comment]
I think I'm missing something. We should have a call about this tomorrow. 

I thought the reason for storing the concatenated name/id in the database was to avoid the performance hit of doing a where clause against two separate columns and trying to join those associated names/ids together.

**Review by cschwinderg — APPROVED** [review]
Works well!

**Pull request merged**
