### PR TITLE
Bugfix/256 latest not returning true latest

### PR DESCRIPTION
**Pull request by cschwinderg**
## Related Issues:
* [EQ-267](https://jira.epa.gov/browse/EQ-267)

## Main Changes:
* Fixed a bug where filters could cause the incorrect reporting cycle to be chosen for the latest query.
  * This was mainly done by removing filters from the sub query, but also by updating the reporting cycle materialized views to also have organization id, region, and state. 
  * As an optimization, I did allow the sub query to be filtered by the `region`, `state`, and `organizationId` filters.
* Added code to prevent the reporting cycle filter from using the `latest` sub query if the user selected something other than `latest` for the reporting cycle. 
  * Before we were doing something like the following if a user selected 2020 for the reporting cycle: `SELECT * FROM <profile> WHERE (organizationid, reportingcycle) IN (SELECT organizationid, max(reportingcycle) FROM <profile> WHERE reportingcycle='2020' GROUP BY organizationid`. 
  * Now we do the following: `SELECT * FROM <profile> WHERE reportingcycle = '2020'`
* Updated the Reporting Cycle field to be filtered by region, state, and organization id. 

## Steps To Test:
1. Verify envs are pointing to local database
2. Run the etl
3. Start the app 
4. Verify the latest reporting cycle filter works as expected
    * A helpful way to check this is to add `console.log('query: ', query.toString());` after line 341 in the `app/server/app/routes/attains.js` file
6. Verify selecting a reporting cycle year as the filter works as expected
7. Verify that selecting a region, state, and or organization id filters the reporting cycle options

### CODE REVIEW

**Review by maxdiebold-erg — COMMENTED** [review]
Seems to work to me, it seems they're all returning the latest cycle. In this block, though, do we still want to add the WHERE clauses to the subquery?

```
 // build where clause of the query
  profile.columns.forEach((col) => {
    const lowArg = 'lowParam' in col && queryParams.filters[col.lowParam];
    const highArg = 'highParam' in col && queryParams.filters[col.highParam];
    const exactArg = queryParams.filters[col.alias];
    if (lowArg || highArg) {
      appendRangeToWhere(query, col, lowArg, highArg);
      if (subQuery) appendRangeToWhere(subQuery, col, lowArg, highArg);
    } else if (exactArg) {
      appendToWhere(query, col.name, queryParams.filters[col.alias]);
      if (subQuery)
        appendToWhere(subQuery, col.name, queryParams.filters[col.alias]);
    }
  });
```
I saw that it results in some WHERE clauses being added twice to the subquery, and it seems that the clauses we want to add are already added in the `createLatestSubquery` function.

**Comment by cschwinderg** [comment]
Good catch! We definitely don't want to add anymore items to the subquerie's where clause than what the `createLatestSubquery` function does.

**Comment by cschwinderg** [comment]
It should be fixed now.

**Review by maxdiebold-erg — APPROVED** [review]
Looks good!

**Pull request merged**
